apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-7ohh
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0025-tenant/ci10t-776-0025-app/devfile-sample-7ohh@sha256:ca5910d41415c97fcfaef4ba198e6e0411637631c26c5f666edc777144648180
        name: my-nodejs
        resources: {}
status: {}
